### ISSUE TITLE
CMPHU CMPHS moved from their v5a location

### ISSUE THREAD

**Issue by lb3361** [at67/ROMvX0#28]
I know you don't like CMPHU/CMPHS, but if they are moved away from their ROMv5a location, many programs compiled for ROMv5a will not run on ROMvX0 (including pretty much all GLCC compiled ones).

If you want space in page 3, I'd rather see you change INCW/DECW into prefix2 instructions.

**Comment by at67** [comment]
CMPHS/CMPHU un-re-instated and moved into the PREFX2 page.
