### ISSUE TITLE
Wait neglects high byte

### ISSUE THREAD

**Issue by axelb68** [at67/ROMvX0#32]
The wait command currently only uses the lower byte. 
In addition wait(0) does not return immediately but waits for 256 frames.   
``` 
_runtimePath_  "../runtime"
_codeRomType_  ROMvX0
CLS

for n = 0 to 512 step 256
	SET TIMER,0
	wait(n)                                                 'always waits for about 4s !
	print "WAIT ";n;" = ";GET("TIMER");"s"   
next n

```

**Comment by at67** [comment]
- This was a design choice making the runtime smaller, the thinking being that if you need larger delays, you can wrap it all in another loop.
- For ROMvX0 only I have replaced the DBNE with a DJNE, (which supports 16bit values as well as far jumps).
- For all previous ROM's the functionality will stay the same, i.e. only an 8bit count is supported.
