### ISSUE TITLE
In PS2 keyboard mode, the Enter key cannot enter the program

### ISSUE THREAD

**Issue by denjhang** [at67/ROMvX0#33]
The old version of ROM (such as DEVROM) can enter the program by pressing the Enter key or other keys in ps2 keyboard mode, but currently ROMvX0 seems to only use the handle A key to enter the program.

**Comment by at67** [comment]
ROMvX0 uses ENTER to set the time on the main menu, DELETE/DEL can be used to start an application. I may change this in the future, but this is how it works right now.
