### ISSUE TITLE
Compiler emits wrong assembly code (missing operand)

### ISSUE THREAD

**Issue by axelb68** [at67/ROMvX0#36]
```
_runtimePath_  "runtime"
_codeRomType_  ROMvX0

dim b(1)
b(0).hi = 0
```
generates the assembly code:

```
...
LDWI                         0x7dfc + 1
POKEI                                                     ; b(0).hi = 0
```
which causes the error: **Assembler::assemble() : 'test.gasm:472' : invalid label/Equate ';'**

The immediate operand of POKEI is missing for values from 0 to 255.

**Comment by at67** [comment]
This bug has been fixed, if you need it fixed in the current release of gtBASIC, then go to line 4617 in optimiser.cpp:
~~~
    std::string immOperand = Expression::getVasmOperand(movqwOperand, 1);
~~~
and change it to:
~~~
    std::string immOperand = Expression::getVasmOperand(Compiler::getCodeLines()[codeLine]._vasm[firstMatch]._operand, 1);
~~~

**Comment by axelb68** [comment]
Thank you!
