### ISSUE TITLE
Bug in SYS_LSLW4

### ISSUE THREAD

**Issue by lb3361** [at67/ROMvX0#37]
The following bug was revealed by the GLCC test sequence

The delay slot of this JMP instruction
https://github.com/at67/ROMvX0/blob/ed7d16568a1c382630cdbc8c9b5cd87c3ad9f0a0/Core/ROMvX0.asm.py#L2862 contains the ST([X]) instruction of line 2870 which belongs to the new opcode LSRB. 
https://github.com/at67/ROMvX0/blob/ed7d16568a1c382630cdbc8c9b5cd87c3ad9f0a0/Core/ROMvX0.asm.py#L2870

As a result, calling SYS_LSLW4 will overwrite the page zero byte whose address is contained in X (which in fact contains the low byte the address of the SYS instruction operand).  This can easily cause trouble. 

The solution is simply to swap lines 2870 and 2871.

**Comment by at67** [comment]
This was internally fixed months ago, closing.
